import assert from 'node:assert/strict';

const store = new Map();
globalThis.chrome = { storage: { local: { async get(keys) { const list = Array.isArray(keys) ? keys : [keys]; return Object.fromEntries(list.map((key) => [key, store.get(key)])); }, async set(values) { Object.entries(values).forEach(([key, value]) => store.set(key, value)); }, async remove(keys) { (Array.isArray(keys) ? keys : [keys]).forEach((key) => store.delete(key)); } } } };
const { clearCompletedTasks, createTask, listTasks, removeTask, setActiveTask, toggleTask } = await import('../shared/tasks-service.js');
const normal = await createTask('Préparer la réunion', 'normal');
const high = await createTask('Finaliser la présentation', 'high');
const low = await createTask('Classer les notes', 'low');
const recurring = await createTask('Revue quotidienne', 'normal', { recurrence: 'daily', dueAt: new Date(Date.now() + 86_400_000).toISOString(), reminderAt: new Date(Date.now() + 82_800_000).toISOString() });
let tasks = await listTasks();
assert.equal(tasks.findIndex((task) => task.id === high.id) < tasks.findIndex((task) => task.id === normal.id), true, 'une tâche de haute priorité non datée doit rester devant une tâche normale non datée');
const active = await setActiveTask(normal.id);
assert.equal(active.id, normal.id);
tasks = await listTasks({ includeDone: false });
assert.equal(tasks.find((task) => task.id === normal.id).active, true);
const completed = await toggleTask(normal.id);
assert.equal(completed.done, true);
tasks = await listTasks({ includeDone: false });
assert.equal(tasks.some((task) => task.id === normal.id), false);
assert.equal((await listTasks()).find((task) => task.id === normal.id).active, false);
const recurringDone = await toggleTask(recurring.id);
assert.equal(recurringDone.done, true);
assert.equal(recurringDone.nextOccurrence.recurrence, 'daily');
assert.equal(recurringDone.nextOccurrence.recurrenceSeriesId, recurring.id);
assert.equal(new Date(recurringDone.nextOccurrence.dueAt) > new Date(recurring.dueAt), true, 'la prochaine occurrence doit avancer l’échéance');
const reopened = await toggleTask(recurring.id);
assert.equal(reopened.done, false, 'une tâche terminée peut être rouverte');
const completedAgain = await toggleTask(recurring.id);
assert.equal(completedAgain.done, true);
assert.equal(completedAgain.nextOccurrence, undefined, 'une nouvelle complétion ne doit pas dupliquer l’occurrence future déjà créée');
tasks = await listTasks({ includeDone: false });
assert.equal(tasks.filter((task) => task.recurrenceSeriesId === recurring.id).length, 1, 'la série ne doit conserver qu’une occurrence future ouverte');
const cleared = await clearCompletedTasks();
assert.equal(cleared.removed, 2, 'le nettoyage doit supprimer les deux occurrences terminées sans supprimer la prochaine occurrence');
const removal = await removeTask(low.id);
assert.equal(removal.removed, true);
await assert.rejects(() => createTask('x'.repeat(241)), /240/);
console.log('tasks-service simulation: ok');
